[build]
command = "npm run build"
publish = "build/client"

[dev]
command = "npm run dev"
framework = "vite"

# 301 redirect to production domain to avoid duplicate content

[[redirects]]
  from = "https://subdomain.netlify.app/*"
  to = "https://yourdomain.com/:splat"
  status = 301
  force = true

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/assets/*"
[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"
