[[redirects]]
  from = "https://paste-image-download.netlify.app/*"
  to = "https://pasteimagetodownload.com/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://pasteimagetodownload.com/*"
  to = "/index.html"
  status = 200
