import React from "react";
import { CurrencyType } from "./CurrencySelector";
import { WithdrawalFrequency } from "@/types/calculator";
import InfoTooltip from "./InfoTooltip";
import DonutChart from "./DonutChart";

interface ResultCardProps {
  totalInvestment: number;
  monthlyInvestment: number;
  totalValue: number;
  currency: CurrencyType;
  sipFrequency: WithdrawalFrequency;
  timePeriod: number;
}

const formatCurrency = (value: number, currency: CurrencyType): string => {
  const currencyFormats: { [key in CurrencyType]: { locale: string, currency: string } } = {
    INR: { locale: "en-IN", currency: "INR" },
    USD: { locale: "en-US", currency: "USD" },
    EUR: { locale: "de-DE", currency: "EUR" },
    JPY: { locale: "ja-JP", currency: "JPY" },
    GBP: { locale: "en-GB", currency: "GBP" },
    CNY: { locale: "zh-CN", currency: "CNY" },
    AUD: { locale: "en-AU", currency: "AUD" },
    CAD: { locale: "en-CA", currency: "CAD" },
    CHF: { locale: "de-CH", currency: "CHF" },
    HKD: { locale: "zh-HK", currency: "HKD" },
    SGD: { locale: "en-SG", currency: "SGD" }
  };

  const format = currencyFormats[currency];
  const formatter = new Intl.NumberFormat(format.locale, {
    style: "currency",
    currency: format.currency,
    maximumFractionDigits: 0,
  });
  return formatter.format(value);
};

const ResultCard = ({
  totalInvestment,
  monthlyInvestment,
  totalValue,
  currency,
  sipFrequency,
  timePeriod,
}: ResultCardProps) => {
  const totalProfit = totalValue - totalInvestment;

  return (
    <div className="border border-border bg-card dark:bg-card rounded-xl p-6 space-y-4">
      <div className="flex justify-between items-center">
        <div className="flex flex-wrap items-center gap-x-1">
          <span className="text-gray-600 dark:text-gray-400">Total</span>
          <span className="text-gray-600 dark:text-gray-400">Investment</span>
          <InfoTooltip content="The total amount you will invest over the entire investment period through SIP." />
        </div>
        <span className="text-xl font-semibold text-foreground">
          {formatCurrency(totalInvestment, currency)}
        </span>
      </div>
      <div className="flex justify-between items-center">
        <div className="flex flex-wrap items-center gap-x-1">
          <span className="text-gray-600 dark:text-gray-400">Total</span>
          <span className="text-gray-600 dark:text-gray-400">Profit</span>
          <InfoTooltip content="The total returns generated by your SIP investment over the investment period." />
        </div>
        <span className={`text-xl font-semibold ${totalProfit > 0 ? 'text-green-500 dark:text-green-400' : 'text-foreground'}`}>
          {formatCurrency(totalProfit, currency)}
        </span>
      </div>
      <div className="flex justify-between items-center">
        <div className="flex flex-wrap items-center gap-x-1">
          <span className="text-gray-600 dark:text-gray-400">Total</span>
          <span className="text-gray-600 dark:text-gray-400">Value</span>
          <InfoTooltip content="The final value of your investment including both your invested amount and the returns generated." />
        </div>
        <span className="text-xl font-semibold text-foreground">
          {formatCurrency(totalValue, currency)}
        </span>
      </div>

      <DonutChart
        totalInvestment={totalInvestment}
        totalWithdrawal={totalProfit}
        currency={currency}
        formatCurrency={formatCurrency}
      />
    </div>
  );
};

export default ResultCard;