// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vslryztolbchzyuhgeni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzbHJ5enRvbGJjaHp5dWhnZW5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNTMxNjMsImV4cCI6MjA1NDgyOTE2M30.VmykK2Fn9OMNWYWK9GWDqUyRrOSg28fiDrZrJgvfxj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);